[build]
  publish = "./"       # Root of your site (index.html lives here)
  command = ""         # Empty because no build step (plain HTML)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
